### ISSUE TITLE
ENV variable names are case sensitive on unix.

### ISSUE THREAD

**Issue by icholy** [bradylove/envstruct#4]
You're [upper-casing](https://github.com/bradylove/envstruct/blob/e42d579b41e72905ab0a5234df74e26bbc6368e5/envstruct.go#L36) all the variable names before looking them up. This makes it impossible to access environment variables that are not all uppercase on unix like systems.

**Comment by bradylove** [comment]
Thanks for pointing this out I will get a fix in asap.

**Comment by bradylove** [comment]
This has been fixed in 94ecb16621c2dc6bf22c029a3ff2e286e95961bd
